### ISSUE TITLE
Configure Liberty with Archaius

### ISSUE THREAD

**Issue by schmitzhermes** [WASdev/sample.netflixoss.wlp#2]
Hey folks,

we are using Liberty extensively and we are struggling with the following question: This liberty feature provides the ability to add configuration via server.xml. That is great. But it'd be even better if we get the chance to _configure_ liberty using Archaius... That means accessing Archaius properties in the server.xml (e.g. database pass / user) directly. 

This means that there'd be a single point of configuration - all through Archaius. 

I know, there are many challenges (what configuration repositories should Archaius look into etc. pp.) - but:  any chance how this is possible? How do you guys handle this "problem"? 

Thanks in advance.

**Comment by davidcurrie** [comment]
Hi Jan

It's something we did consider but to do it well would require changes to the Liberty runtime as the internals are very much built around loading configuration files. Using that as a starting point though, there are various Liberty features that can help. For example, you can embed environment variables in to configuration using the syntax ${env.YYYY}. Alternatively, the mechanism used by the Liberty buildpack for example, is to generate a configuration file which encodes the properties as Liberty variables which are then used throughout the server configuration. If the configuration you need to inject is more complicated (e.g. you need to add whole new XML stanzas when a property exists) then I know of at least one customer who is using a templating technology (jinja in their case) to generate the config before the server starts up. The use of configDropins to extend some base configuration is also a useful technique.

Regards
David
